
-- 8 no question
            SELECT MIN(SALARY)
			FROM EMPLOYEES
			WHERE SALARY >(
							SELECT MIN(SALARY)
							FROM EMPLOYEES
						   );
use programminghero;

CREATE TABLE EMPLOYEES
(
EmployeeID INT PRIMARY KEY ,
NAME VARCHAR (50),
EMAIL VARCHAR (50),
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID) ON DELETE SET NULL
);
CREATE TABLE JOB_HISTORY
(
JOB_ID INT PRIMARY KEY,
STRTDATE DATE,
END_DATE date,
EmployeeID INT ,
FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES (EmployeeID) ON DELETE CASCADE

);
CREATE TABLE DEPARTMENT
(
 DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR (50) ,
 MANAGER_ID INT,
 LOCATION_ID INT
)
